repos:
-   repo: https://github.com/uktrade/pii-secret-check-hooks
    rev: 0.0.0.17
    hooks:
    -   id: pii_secret_filename
        files: ''
        language: python
        pass_filenames: true
    -   id: pii_secret_file_content
        files: ''
        language: python
        pass_filenames: true
    -   id: hooks_version_check
        name: Checking local hooks against latest release
        verbose: true
