version: "3"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  helpcentre:
    build:
       context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
  helpcentre-sso.test:
    build: https://github.com/uktrade/mock-sso.git
    environment:
      - MOCK_SSO_PORT=8081
      - MOCK_SSO_TOKEN=bar
      - MOCK_SSO_CODE=fizz
    ports:
      - "8081:8081"

