version: "3"
services:
#  wagtail:
#    build:
#      context: helpdesk
#      dockerfile: Dockerfile
#    env_file: .env
#    links:
#      - "postgres"
#    image: data-hub-helpdesk
#    ports:
#      - "8000:8000"
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    env_file: .env
