# Generated by Django 4.2.15 on 2024-09-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inline_feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinlinefeedbacksurvey",
            name="inline_feedback_choices",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userinlinefeedbacksurvey",
            name="more_detail",
            field=models.TextField(blank=True, default=""),
        ),
    ]
