# Generated by Django 2.2.8 on 2020-02-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0008_articlehomepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlehomepage",
            name="show_recent_child_articles",
            field=models.BooleanField(default=True),
        ),
    ]
