# Generated by Django 3.2.13 on 2022-05-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_articlepage_body'),
        ('article', '0014_articleindexpage_children_order'),
    ]

    operations = [
    ]
