# Generated by Django 3.2.13 on 2022-05-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220503_1206'),
        ('user', '0002_auto_20220510_0943'),
    ]

    operations = [
    ]
